ww07.2 MediaSDK release for Android O KBL
MediaSDK product version: 6.0.013691
MediaSDK file version: 6.18.2.13

Android tree information:
- 1Android O Master branch;
- icl_presi_kbl-userdebug target;
- Media SDK projects:
  project mdp_msdk-lib, revision master;
  project mdp_msdk-contrib revision master;
  project mdp_msdk-api revision master;
  project mdp_msdk-omx-plugins revision master;
  project mdp_msdk-ipp_7_1-bin revision master.

List of changes for MediaSDK samples OpenMAX plug-ins:
- Added LibVA 2.0 support

List of changes for LibVA:
- Enabled libVA master on Android O
  (I1e7359a6215000d8adb429f9c41d51bbed8acc66)

List of changes for HW composer:
- Fixed hwc compilation error due to libva master upgrade
  (Ifa8663e178b48fdb24ad35d1de71c26b643da374)

List of changes for libmediaparser:
- Removed va-tpi for libva master upgrade
  (I7798f19f03627a8a8f02c4fe6b651ef653455bd7)

Android O Master branch:
- MediaSDK library: [vp9e] Fixed test parameters
  (Ib541f12469728a20b65e83fa7ee3c10eeed5b77b)
- MediaSDK samples OpenMAX plug-ins:
  Fix CTS regression after nFilledLen modification
  (I07bc94fcdde6421fedc7e35e4c6a30a16716a1a6)
- UFO GEN9: Fix the pavp create section failure
  (Ie85ef3c22ba2ade73af9b1fb9d49d10bd6474c52)
- LibVA: Extend the search scope of c header files
  (I7ab4ec36183e349a0feec4c6320362af1a1d78e6)

Change-Id: Ibbf083ae86152568aaf3ebf306b533f4a85d7896
Signed-off-by: Olga Kasatkina <olga.a.kasatkina@intel.com>
Tracked-On: https://jira01.devtools.intel.com/browse/OAM-57310
Reviewed-on: https://android.intel.com:443/619192